title: Hash Viewer
author:
  name: "Matthew Wildrick Thomas"
  website: "https://www.matthewthom.as"

tagline: "Share Math and Markdown"
description: "Hash Viewer lets you display and share Markdown, HTML, and LaTeX without any server side-components. It works by storing page content in the URL."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hash.mwt.me" # the base hostname & protocol for your site, e.g. http://example.com

social:
  name: Hash Viewer
  links:
    - "https://github.com/mwt/hash-viewer"
    - "https://www.producthunt.com/posts/hash-viewer"
    - "https://angel.co/projects/1258295-hash-viewer"
    - "https://alternativeto.net/software/hash-viewer/about/"
    - "https://devmesh.intel.com/projects/hash-viewer"

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-octicons

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore
  - package.json
  - package-lock.json
  - build.js
  - node_modules/
